# Site settings
title: Woopsa â€“ Web Object-Oriented Protocol for Software and Automation
email: woopsa@objectis.ch
description: > # this means to ignore newlines until "baseurl:"
  Woopsa is a protocol that's simple, lightweight, free, open-source, 
  web and object-oriented, publish-subscribe, real-time capable and 
  Industry 4.0 ready. It contributes to the revolution of the Internet of Things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.woopsa.org" # the base hostname & protocol for your site
github_username:  woopsa-protocol
permalink: /:categories/:title
# Build settings
markdown: kramdown
